### ISSUE TITLE
Add Rainfall to Forecasts

### ISSUE THREAD

**Issue by NicGray78** [tomitan100/org.openhab.binding.bom#1]
Hi Thomas,

I noticed that the amount of forecast rainfall is missing on Day2-8, it looks like BOM give you a range, so for ease of use in rules / evaluations, is it possible to add 2 additional channels, Min Rainfall and Max Rainfall, then people can choose which values they want to grab?

**Comment by tomitan100** [comment]
Done.  The two new fields are called _Minimum Precipitation_ and _Maximum Precipitation_ instead of _Min Rainfall_ and _Max Rainfall_ respectively.

I have also added 24 hour rainfall as part of this change.
