### ISSUE TITLE
Manual Configuration

### ISSUE THREAD

**Issue by howesij** [tomitan100/org.openhab.binding.bom#3]
Hi,

I am configuring my Openhab manually was wondering if you had a cfg file or could tell me what would need to go in a configuration file?

cheers

**Comment by tomitan100** [comment]
Hi, not too sure what you mean exactly.  You should be able to use the following files.

[bom.items](https://github.com/tomitan100/org.openhab.binding.bom/raw/master/doc/bom.items)

[bom.sitemap](https://github.com/tomitan100/org.openhab.binding.bom/raw/master/doc/bom.sitemap)

You can read about sitemap config here: [Sitemaps](https://www.openhab.org/docs/configuration/sitemaps.html)


Regards,
Tom
