### ISSUE TITLE
Openhab 3

### ISSUE THREAD

**Issue by paulplac** [tomitan100/org.openhab.binding.bom#6]
Hi Tom,

First up thanks for the awesome binding.

Do you plan to update the binding for Openhab 3?  I would hate to have to revert to my poorly built, under featured nodered flow that i used to use.

Best regards
Paul

**Comment by tomitan100** [comment]
Hi Paul,

It's available now.  Let me know if there is any issue.


Regards,
Tom

**Comment by paulplac** [comment]
Hi Tom,

Installed and running beautifully in OH3.  Thank you so much.
